name: Veracode React Sample App

on:
  push:
    branches: ['\d+.x']
  pull_request:
    branches: ['\d+.x']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}

      - name: 'Delete spec files'
        run: find . -type f -name '*.spec.ts' -delete

      - name: 'Delete reportWebVitals files'
        run: find . -type f -name 'reportWebVitals.ts' -delete

      - name: 'Delete type files'
        run: find . -type f -name '*.d.ts' -delete

      - name: 'create an empty ./veracode folder'
        run: 'mkdir -p ./veracode'

      - name: 'Compress react-sample-app'
        run: tar -czvf ./veracode/react-ample-app.tar.gz ./src

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-sample-app
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./veracode

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'lf-sample-OAuth-SPA-react'
          createprofile: true
          filepath: 'veracode'
          vid: '${{ secrets.VERACODE_API_ID }}'
          vkey: '${{ secrets.VERACODE_API_KEY }}'
          teams: 'Application Component - Shared'

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.6
        with:
          create-issues: false
          allow-dirty: true
          recursive: true
